import { type Models } from 'appwrite';

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l ts /Users/daniel.veremchuk/personal/cuapp/appwrite`.
 */

export enum DeliveryStatus {
  SENT = "sent",
  DELIVERED = "delivered",
  READ = "read"
}

export enum MessageType {
  TEXT = "text",
  IMAGE = "image"
}

export enum Permissions {
  PRIVATE = "private"
}

export enum PostType {
  IMESSAGE_CONVERSATION = "imessageConversation",
  IMAGE_POST = "imagePost",
  TEXT_POST = "textPost"
}

export enum Status {
  PUBLISHED = "published",
  DRAFT = "draft",
  ARCHIVED = "archived"
}

export enum AccessLevel {
  PUBLIC = "public",
  PRIVATE = "private",
  FOLLOWERS = "followers",
  MUTUALS = "mutuals",
  UNLISTED = "unlisted",
  TEAM = "team"
}

export type ImessageMessages = Models.Document & {
  conversationId: string;
  messageId: string;
  participantDocId: string;
  content: string;
  timestamp: string;
  timestampDisplay: string | null;
  isEdited: boolean;
  screenshotIndex: number;
  deliveryStatus: DeliveryStatus | null;
  messageType: MessageType;
  imageUrl: string | null;
  imageFileId: string | null;
  imageAltText: string | null;
}

export type Profiles = Models.Document & {
  username: string;
  bio: string | null;
  profileImage: string[] | null;
  permissions: Permissions[] | null;
}

export type TextPost = Models.Document & {
  postId: string;
  body: string;
  coverImageFileId: string | null;
  coverImageAltText: string | null;
  version: number | null;
  estimatedReadTimeMinutes: number | null;
  contentSchemaVersion: string | null;
}

export type Posts = Models.Document & {
  userId: string;
  postType: PostType;
  tags: string[] | null;
  status: Status;
  accessLevel: AccessLevel;
  contentRefId: string | null;
  likesCount: number;
  commentsCount: number;
  title: string;
}

export type ImessageParticipants = Models.Document & {
  userId: string;
  name: string;
  avatarFileId: string | null;
}

export type ImessageConversation = Models.Document & {
  postId: string;
  participantDocRefs: string[];
  rightSideParticipantDocRef: string;
  screenshotMessageIds: string[];
  totalScreenshots: number;
  conversationId: string;
}

